sample_app/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'proxy' => 'proxy#index'
  resources :users, only: [:index, :show]
end

sample_app/app/models/user.rb
class User < ActiveRecord::Base
  def age
    date_format = "%Y%m%d"
    today_timestamp = Date.today.strftime(date_format).to_i
    birth_date_timestamp = birth_date.strftime(date_format).to_i
    (today_timestamp - birth_date_timestamp) / 10000
  end
end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sample_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

sample_app/app/controllers/proxy_controller.rb
class ProxyController < ApplicationController
  def index
    render html: Net::HTTP.get(URI('https://example.com/')).html_safe
  end
end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
end

sample_app/app/views/home/index.html.slim
#home
  h1 Puma vs Unicorn
  p Sample application.
  .links
    = link_to 'Users', users_path
    = ' / '
    = link_to 'Proxy', proxy_path

sample_app/app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    link href="//cdn.muicss.com/mui-0.5.3/css/mui.min.css" rel="stylesheet" type="text/css"
    = stylesheet_link_tag 'application', media: 'all'
    title Puma vs Unicorn
  body
    header.mui-appbar.mui--z1
      .mui-container
        table width="100%"
          tr.mui--appbar-height
            td.mui--text-title
              a.title_link href="/" Puma vs Unicorn
            td align="right"
    #content-wrapper
      == yield
    script src="//cdn.muicss.com/mui-0.5.3/js/mui.min.js"
    = javascript_include_tag 'application'

sample_app/app/views/users/index.html.slim
#users_index
  h1= User.model_name.human
  - if @users.present?
    table.mui-table.mui-table--bordered
      thead
        tr
          th= User.human_attribute_name :name
          th= User.human_attribute_name :age
          th= User.human_attribute_name :mail
      tbody
        - @users.each do |user|
          tr
            td= link_to user.name, user_path(user)
            td= user.age
            td= user.mail
  - else
    .mui-pane
      .mui--text-dark-secondary.mui--text-display1
        p Record not found.

sample_app/app/views/users/show.html.slim
#users_show
  = link_to 'List', users_path
  h1= @user.name
  table
    tr
      th= User.human_attribute_name :mail
      td= @user.mail
    tr
      th= User.human_attribute_name :age
      td= @user.age
    tr
      th= User.human_attribute_name :birth_date
      td= @user.birth_date.strftime('%Y/%m/%d')